package com.seatbooking.dto;

import java.time.LocalDateTime;

public class EventResponseDTO { //Transfer event data from the server to the client, specifically for responding to event-related requests

    // Unique Event ID generated by the database
    private Long eventId;

    // Name of the Event
    private String name;

    // Type of Event
    private String eventType;

    // Event Start Time
    private LocalDateTime eventStartTime;

    // Booking Open Time
    private LocalDateTime bookingOpenTime;

    // Booking Close Time
    private LocalDateTime bookingCloseTime;

    // Maximum seats allowed per user
    private Integer maxSeatsPerUser;

    // Default Constructor
    public EventResponseDTO() {
    }

    // Parameterized Constructor
    public EventResponseDTO(
            Long eventId,
            String name,
            String eventType,
            LocalDateTime eventStartTime,
            LocalDateTime bookingOpenTime,
            LocalDateTime bookingCloseTime,
            Integer maxSeatsPerUser) {

        this.eventId = eventId;
        this.name = name;
        this.eventType = eventType;
        this.eventStartTime = eventStartTime;
        this.bookingOpenTime = bookingOpenTime;
        this.bookingCloseTime = bookingCloseTime;
        this.maxSeatsPerUser = maxSeatsPerUser;
    }

    // Getter and Setter for Event ID
    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    // Getter and Setter for Event Name
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // Getter and Setter for Event Type
    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    // Getter and Setter for Event Start Time
    public LocalDateTime getEventStartTime() {
        return eventStartTime;
    }

    public void setEventStartTime(LocalDateTime eventStartTime) {
        this.eventStartTime = eventStartTime;
    }

    // Getter and Setter for Booking Open Time
    public LocalDateTime getBookingOpenTime() {
        return bookingOpenTime;
    }

    public void setBookingOpenTime(LocalDateTime bookingOpenTime) {
        this.bookingOpenTime = bookingOpenTime;
    }

    // Getter and Setter for Booking Close Time
    public LocalDateTime getBookingCloseTime() {
        return bookingCloseTime;
    }

    public void setBookingCloseTime(LocalDateTime bookingCloseTime) {
        this.bookingCloseTime = bookingCloseTime;
    }

    // Getter and Setter for Maximum Seats Per User
    public Integer getMaxSeatsPerUser() {
        return maxSeatsPerUser;
    }

    public void setMaxSeatsPerUser(Integer maxSeatsPerUser) {
        this.maxSeatsPerUser = maxSeatsPerUser;
    }
}