package com.seatbooking.scheduler;

import com.seatbooking.entity.Seat;
import com.seatbooking.repository.SeatRepository;
import com.seatbooking.enums.SeatStatus;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import org.slf4j.Logger; //recording scheduler activities.
import org.slf4j.LoggerFactory; //creates a logger associated with this class

import java.time.LocalDateTime;
import java.util.List;

@Component
public class SeatUnlockScheduler {

    private static final Logger logger =
            LoggerFactory.getLogger(SeatUnlockScheduler.class); //Every log generated by this class will be associated with the SeatUnlockScheduler class

    @Autowired 
    private SeatRepository seatRepository;

    /**
     * Runs every minute
     *
     * Finds:
     * LOCKED seats
     * whose lock time has expired
     *
     * Converts them back to AVAILABLE
     */
    @Scheduled(fixedRate = 60000)
    public void releaseExpiredLocks() {

        List<Seat> expiredSeats =
                seatRepository.findByStatusAndLockExpiryTimeBefore(
                        SeatStatus.LOCKED,
                        LocalDateTime.now()
                );

        for (Seat seat : expiredSeats) {

            seat.setStatus(SeatStatus.AVAILABLE);

            seat.setLockedByUser(null);

            seat.setLockExpiryTime(null);

            seatRepository.save(seat);
        }

        if (!expiredSeats.isEmpty()) {

            logger.info(
                "{} expired seat locks released.",
                expiredSeats.size()
            );
        }
    }
}